-- Purvaj Backend Details

CREATE DATABASE IF NOT EXISTS PURVAJ;
use PURVAJ;

DROP TABLE IF EXISTS Data;
CREATE TABLE IF NOT EXISTS Data(
	Id INT NOT NULL,
	ParentId INT NOT NULL,
	Name VARCHAR(255) NOT NULL,
	Attributes JSON,
	IsApproved Bool DEFAULT 0,
	CreatedBy INT,
	CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (Id)
);

DROP TABLE IF EXISTS Attributes;
CREATE TABLE  IF NOT EXISTS Attributes(
	AttributeId INT NOT NULL,
	AttributeaName VARCHAR(255),
	AttributeType VARCHAR(255),
	IsRequired BOOL DEFAULT 0,
	PRIMARY KEY (AttributeId)
);
DROP TABLE IF EXISTS UserDetail;
CREATE TABLE  IF NOT EXISTS UserDetail(
	UserId INT NOT NULL,
	UserName VARCHAR(255) NOT NULL,
	Password VARCHAR(255) NOT NULL,
	UserRoleId INT NOT NULL,
	CreatedBy INT NOT NULL,
	CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (UserId)
);

DROP TABLE IF EXISTS Roles;
CREATE TABLE IF NOT EXISTS Roles(
	RoleId INT NOT NULL,
	RoleName VARCHAR(255)
);

DROP TABLE IF EXISTS Dashboard;
CREATE TABLE IF NOT EXISTS Dashboard(
	DashboardId INT NOT NULL,
	DashboardName VARCHAR(255),
	NodeId INT,
	PreLimit INT,
	PostLimit INT,
	TTL INT,
	CreatedBy INT,
	CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS DashboardCache;
CREATE TABLE IF NOT EXISTS DashboardCache(
	DashboardId INT NOT NULL,
	Data TEXT,
	CachedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS ChangeRequest;
CREATE TABLE IF NOT EXISTS ChangeRequest(
	RequestId INT NOT NULL,
	PreviousData JSON,
	UpdatedData JSON,
	RequestedBy INT,
	RequestedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS ChangeNodes;
CREATE TABLE IF NOT EXISTS ChangeNodes(
	RequestId INT NOT NULL,
	NodeId INT,
	RequestedBy INT,
	RequestedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
